encrypted_password: ENC[AES256_GCM,data:np28,iv:hCdgBBnwm83+jX4fmo6AF36Ug7mJ8+h9YSPmZ/JMM8c=,tag:ELu2OU5kumjafu0ObqDZsg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age: []
  lastmodified: "2022-01-23T21:53:24Z"
  mac: ENC[AES256_GCM,data:g5eUz1TQ9krZPqokyyxmzVuDJVJ3wymXIc2Hm3OWB04FO/1FhzmWeMM+aFbZtU2Xyva9u0e8GSDOnAvVOB9Zo5uJaadTOn6gaboRG3M1BTvZRj4yF3m1h5gO+puMMJ6g2jCArndJr+UHgq7clP7vEiSHRpgcfJIZnicLJXfEVo0=,iv:RG/R2FVFG1Lieqz6pY5J2Ycsb/XrHJqvyTBAyJxdOts=,tag:JtxINWcVWaTP6kVSxN6x6g==,type:str]
  pgp:
    - created_at: "2022-01-23T21:53:08Z"
      enc: |
        -----BEGIN PGP MESSAGE-----

        hQGMA8GMu2ELlYPEAQv/bvvFQ0kbgvzatmpDufrJbLLdTy3zsm1TPPbsJ75HQFOM
        EBR+953rbm21VLCabqh10SLf7bZEWndcdvGWv9r2xSB7srJJCIyFx8sUN6bZf66U
        qvWzhWToOCZgkjZj+wS3xT/ELC9OQ5NaLG3LKKUrlsQjMmGYfHuxEgRQyWaOXi2p
        Q0ghU/LSjgCahHOhBFZgmHj60i+T1QViAi13QCMKRghvOpqvinCDDFv20SJ+6eFV
        l4XioL2o2yXcCkay0raHoOcDCRaohR8r0Q0j7LGY4OEGs9RkWNJrUP/SBBleLpFN
        878U3QNYaJ6t28gg9suVHFLibyu0sOmN2L7E96x+6g3JY5eHL4mAYKvixIREzdAF
        LJDHgVjmT63AOTI9qVRkvhQUqYSoj54HyX658CB+QE0ZN/D9hfH9sBQXPsTAzMBA
        4xX8fSpwdbbGuhkuCH4vp9ayK6Epb8gb42qlo18yvcV0r6V8mbjXeGTM+TO7MZaC
        rAyXKqumpWZyW8vINWQ+0l4B5insHQsRnsr+oSKcFFhfb5yt0LXBPy6/DEpMca8Q
        xz4GQQ1HBSwT7+pRLsOVNotvLTKPsovNYSH4zXzN8qy8uh2HB4vDnnluJ+s47Kop
        RtWWTxcYsB43aI2uNs5n
        =ju/S
        -----END PGP MESSAGE-----
      fp: 018EDB11D4B4E1F9DF31B8DC73376C139E21F432
  unencrypted_suffix: _unencrypted
  version: 3.7.1
