version: '2'
services:
  ubuntu1.test:
    image: ubuntu-test-server
    hostname: ubuntu1.test
    ports:
      - "2224:22"
  ubuntu2.test:
    image: ubuntu-test-server
    hostname: ubuntu2.test
    ports:
      - "2225:22"

  centos1.test:
    image: centos-test-server
    hostname: centos1.test
    ports:
      - "2226:22"
