version: '2'
services:
  app1.test:
    image: test-server
    hostname: app1.test
    ports:
      - "2224:22"
  app2.test:
    image: test-server
    hostname: app2.test
    ports:
      - "2225:22"
  db.test:
    image: test-server
    hostname: db.test
    ports:
      - "2226:22"