---
version: '2'
services:
  ubuntu1.test:
    image: ubuntu-test-server
    build:
      context: ./
      dockerfile: ubuntu.Dockerfile
    container_name: ubuntu1
    hostname: ubuntu1.test
    ports:
      - "22"
    networks:
      - private
  centos1.test:
    image: centos-test-server
    build:
      context: ./
      dockerfile: centos.Dockerfile
    container_name: centos1
    hostname: centos1.test
    ports:
      - "22"
    networks:
      - private

  bastion:
    image: bastion-test
    build:
      context: ./
      dockerfile: bastion.Dockerfile
    container_name: bastion
    hostname: bastion.test
    ports:
      - "2222:22"
    networks:
      - private
      - bastion

networks:
  private:
    internal: true
  bastion:
    driver: bridge
