---
- name: Test nonroot user
  hosts: all

  vars_files:
    - ../vars/create-folder.yml

  handlers:
    - import_tasks: ../handlers/create-folder.yml

  tasks:
    - name: Creates directory
      register: new
      file:
        path: "{{ PATH }}"
        state: directory
        recurse: yes
      notify: print diff

    - name: Check folders permission
      command: "ls -la {{ PATH }}"
      register: ls
      notify: print ls
      # changed_when: false
