---
- name: Test nonroot user
  hosts: all

  vars_files:
    - ../vars/create-folder.yml

  handlers:
  - name: print diff
    debug:
      var: new.diff
      verbosity: 1
  
  - name: print ls
    debug:
      var: ls.stdout_lines
      verbosity: 1

  tasks:
    - name: Creates directory
      register: new
      file:
        path: "{{PATH}}"
        state: directory
        recurse: yes
      notify: print diff

    - name: Check folders permission
      command: "ls -la {{PATH}}"
      register: ls
      notify: print ls
