---
- name: Ensure installation
  hosts: all
  become: yes

  vars_files:
    - ../vars/install.yml

  pre_tasks:
    - name: Update cache if needed
      apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - { role: roles/nodejs }

  tasks:
    - name: "Ensure {{ install_package }} is present"
      apt:
        name: "{{ install_package }}"
        state: present

    - name: Download sops binary
      get_url:
        url: "https://github.com/mozilla/sops/releases/download/v{{ sops_version }}/sops-v{{ sops_version }}.linux"
        checksum: "{{ sops_checksum }}"
        dest: /usr/bin/sops
        owner: root
        group: root
        mode: u+rwx,go=rx
